BACKBONE:
  PCD:
    CHANNELS: [ 32, 32, 64, 128, 256, 256, 128, 96, 96 ]
    KNN_UP: 3
    RESOLUTION: 0.05
    INPUT_DIM: 4
    PRETRAINED: ckpt/mink_panoptic.ckpt
    FREEZE: True
  IMG:
    RESOLUTION: 0.1
    INPUT_DIM: 3
    FREEZE: False
  FUSION:
    ENABLE: True
    N_LEVELS: 4
    N_HEADS: 1
    ENABLE_CA: False
