BACKBONE:
    CHANNELS: [ 32, 32, 64, 128, 256, 256, 128, 96, 96 ]
    KNN_UP: 3
    MINK:
        RESOLUTION: 0.05
        INPUT_DIM: 4
        MODALITY: xyzi
        PRETRAINED: ckpt/fusion_pls_semkitti_mn_backbone.ckpt
        FREEZE: True
    CPE:
        RESOLUTION: 0.1
        INPUT_DIM: 3
        MODALITY: rgb
        PRETRAINED: ckpt/fusion_pls_semkitti_mn_backbone.ckpt
        FREEZE: False
    FUSION:
        N_LEVELS: 4
        N_HEADS: 1
        OUT_DIM: [256, 256, 256, 256]
        DIM_FFN: 512
        DROPOUT: 0.0
        HIDDEN_DIM: 256
        NUM_QUERIES: 100
        POS_ENC:
            MAX_FREQ: 10000
            DIMENSIONALITY: 3
            BASE: 2


