BACKBONE:
    CHANNELS: [ 32, 32, 64, 128, 256, 256, 128, 96, 96 ]
    RESOLUTION: 0.05
    KNN_UP: 3
    MINK:
        INPUT_DIM: 4 # coords + intensity
        PRETRAINED: ckpt/fusion_pls_semkitti_mn_backbone.ckpt
    CPE:
        INPUT_DIM: 7 # coords + intensity + rgb
        PRETRAINED: ckpt/fusion_pls_semkitti_ef_backbone.ckpt
    FUSION:
        N_LEVELS: 4
        N_HEADS: 1
        OUT_DIM: [256, 128, 96, 96]
        DIM_FFN: 1024
        DROPOUT: 0.0
        POS_ENC:
            MAX_FREQ: 10000
            DIMENSIONALITY: 3
            BASE: 2


