DECODER:
  NUM_QUERIES: 100
  D_MODEL: 256
  FEATURE_LEVELS: 3

  PANOPTIC:
    NUM_HEADS: 8
    D_FFN: 1024
    DEC_BLOCKS: 1
    DROPOUT: 0.0

  INSTANCE:
    ENABLE: False
    DEC_BLOCKS: 1

  SEMANTIC:
    ENABLE: False
    DEC_BLOCKS: 1

  POS_ENC:
    MAX_FREQ: 10000
    DIMENSIONALITY: 3
    BASE: 2
    RANGE:
      [ 48.0, 48.0, 4.0 ]
